# Generated by Django 4.1.2 on 2022-10-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='accounts.subject', verbose_name='Предмет'),
        ),
    ]
