# Generated by Django 4.1.3 on 2022-11-09 14:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='default-profile-img.jpg', upload_to=accounts.models.user_directory_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('ACCOUNTANT', 'Бухгалтер'), ('TEACHER', 'Преподаватель')], max_length=20),
        ),
    ]
