# Generated by Django 4.1.3 on 2022-11-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardnews',
            options={'ordering': ('-date_added',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='boardnews',
            name='image',
            field=models.ImageField(blank=True, upload_to='board_images'),
        ),
    ]
